### ISSUE TITLE
Add to Cart / Shopping Cart functionality

### ISSUE THREAD

**Issue by fsheremetyeva** [fsheremetyeva/WD6-ProjectPortfolio#2]
As a customer I want to be able to add items I am interested in into the shopping cart.

**Comment by jessicakarpovich** [comment]
I want to be able to click on the Shopping Cart and see what items are in there. It would be nice to see a small picture of the item and the price as well. That would make it easier to identify the items I selected in case there is more than one item with a similar name. For example, two versions of the same book.

**Comment by jessicakarpovich** [comment]
Shopping cart viewable and items can be added as of #13.
